exclude_patterns:
  - "tests/"
  - "spec/"
  - "**/vendor/"
  - "**/node_modules/"
  - "package-lock.json"
  - "package.json"
  - "*.md"
  - "**/*.spec.js"
  - "**/*.test.js"
  - "**/src/components/Auth/"
  - "**/src/components/Navigation/"
